version: "3"
services:
    gptVNC:
        image: accetto/debian-vnc-xfce-firefox-g3
        container_name: gptVNC
        environment:
           VNC_PASSWD: "headless"
           NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
        restart: always
        ports:
         - 59201:5901
         - 29301:6901
         - 44355:4455
        volumes:
            - config:/config
volumes:
    config:
